import "server-only";

/**
 * Portal i18n. Small dictionary kept inline (under ~120 phrases) instead
 * of leaning on the marketing i18n setup — the portal copy is finite and
 * scoped, so a flat object is the simplest source of truth.
 *
 * Resolution order:
 *   1. client_portal_access.preferred_language  (if set by the client)
 *   2. engagements.language                     (defaults to 'en')
 *   3. 'en'                                     (hard fallback)
 */

export type PortalLang = "en" | "es";

type Dict = Record<string, string>;

const EN: Dict = {
  // Sidebar
  "nav.activity": "Activity",
  "nav.resumen": "Overview",
  "nav.bandeja": "Inbox",
  "nav.requires_action": "Requires action",
  "nav.your_agents": "Your agents",
  "nav.insights": "Insights",
  "nav.customers": "Customers",
  "nav.integrations": "Integrations",
  "nav.analytics": "Analytics",
  "nav.account": "Account",
  "nav.settings": "Settings",
  "nav.support": "Support",
  "session.7day": "7-day session",

  // Resumen
  "resumen.eyebrow": "Last 7 days · live",
  "resumen.greeting": "Hello, {name}",
  "resumen.desc": "Here's what your Loucels agent did for {client} this week. Anything that needs your brain is highlighted below.",
  "resumen.recap_title": "Loucels recap",
  "resumen.cta_pending": "{n} pending approval{plural}",
  "resumen.cta_view_inbox": "Open inbox",

  "metric.leads": "Leads processed",
  "metric.leads_sub": "Conversations · last {n} days",
  "metric.bookings": "Bookings confirmed",
  "metric.bookings_sub": "On your calendar",
  "metric.hours": "Hours recovered",
  "metric.hours_sub": "Estimated · {n} min per conversation",

  // Money button
  "money.clear_eyebrow": "All clear",
  "money.clear_title": "Your agent ran solo this week.",
  "money.clear_desc": "Nothing waiting on you. The agent stayed within the rules we set together.",
  "money.alert_eyebrow": "Action required",
  "money.alert_title": "{n} approval{plural} waiting on you",
  "money.alert_desc": "Your agent has {n} action{plural} ready but wants your sign-off before sending.",
  "money.high_risk": "At least one is high risk.",
  "money.review_now": "Review now",
  "money.more": "+{n} more",

  // Today agenda widget
  "today.title": "Today on the calendar",
  "today.empty": "Nothing on the books for today yet.",
  "today.more": "+{n} more later today",

  // Live activity widget
  "live.title": "Live activity",
  "live.empty": "When your agent is busy, you'll see actions stream here.",
  "live.refresh": "auto-refreshes",

  // Inbox
  "inbox.title": "Inbox",
  "inbox.desc": "Every clean transcript between your customers and the agent.",
  "inbox.count": "{n} conversation{plural} in the last 30 days.",
  "inbox.search_soon": "Search (coming soon)",
  "inbox.visitor": "Visitor {short}",
  "inbox.empty_title": "No conversations yet",
  "inbox.empty_desc": "When someone talks to your agent, the chat shows here in plain language — no tech jargon.",
  "inbox.select_one": "Pick a conversation from the left.",
  "inbox.tag_apply": "Tag this",
  "inbox.tag_filter": "Filter by tag",
  "inbox.take_over": "Take over",
  "inbox.take_over_active": "You're driving this conversation",
  "inbox.take_over_release": "Release back to agent",
  "inbox.send_as_owner": "Send as you",
  "inbox.send": "Send",
  "inbox.composer_placeholder": "Type your message…",
  "inbox.agent_paused": "Agent paused. You're handling this conversation manually.",

  "tag.complaint": "Complaint",
  "tag.booking": "Booking",
  "tag.info_request": "Info request",
  "tag.follow_up": "Follow up",
  "tag.spam": "Spam",
  "tag.vip": "VIP",
  "tag.urgent": "Urgent",
  "tag.sale_lost": "Sale lost",
  "tag.sale_won": "Sale won",

  // Requires action
  "ra.title": "Requires action",
  "ra.subtitle_pending": "{n} action{plural} waiting for your go-ahead.",
  "ra.subtitle_empty": "Your agent is shipping on its own. Nothing to decide.",
  "ra.subtitle_no_agent": "Placeholder for future approvals.",
  "ra.history_title": "Decision history",
  "ra.history_eyebrow": "Last 20",
  "ra.clear_title": "All clear",
  "ra.clear_desc": "Your agent stayed within the rules. Nothing waiting on you.",
  "ra.action.send_message": "Send message",
  "ra.action.send_quote": "Send quote",
  "ra.action.send_refund": "Process refund",
  "ra.action.reply_review": "Reply to review",
  "ra.high_risk": "High risk",
  "ra.medium_risk": "Medium risk",
  "ra.proposed_label": "What the agent wants to send:",
  "ra.edit_label": "Edit the message",
  "ra.reject_label": "Why? (optional)",
  "ra.reject_placeholder": "I'll write it myself / wrong info / not ready yet",
  "ra.btn_approve": "Approve and send",
  "ra.btn_modify": "Modify",
  "ra.btn_reject": "Reject",
  "ra.btn_approve_edited": "Approve edited version",
  "ra.btn_confirm_reject": "Confirm rejection",
  "ra.btn_cancel": "Cancel",
  "ra.btn_back": "Back",
  "ra.realtime_hint": "Sends instantly via email",
  "ra.stub_hint": "Confirmation within 1 business hour",
  "ra.approved_realtime": "Sent",
  "ra.approved_stub": "Approved",
  "ra.approved_realtime_desc": "Message went out immediately.",
  "ra.approved_stub_desc": "Loucels is executing — confirmation within 1 business hour.",
  "ra.rejected": "Rejected",
  "ra.rejected_desc": "Your agent will not send this action.",
  "ra.error": "We couldn't process the action ({reason}). Try again or email steven@loucels.com.",
  "ra.recipient": "Recipient",

  // Customers
  "customers.title": "Customers",
  "customers.desc": "Everyone who's talked to your agent — sessions, bookings, history.",
  "customers.empty_title": "No customers yet",
  "customers.empty_desc": "Once visitors start chatting, they show up here as profiles you can drill into.",
  "customers.count": "{n} unique people",
  "customers.col_name": "Name",
  "customers.col_sessions": "Sessions",
  "customers.col_bookings": "Bookings",
  "customers.col_first": "First seen",
  "customers.col_last": "Last seen",

  // Customer detail
  "customer.back": "All customers",
  "customer.history_title": "Conversation history",
  "customer.bookings_title": "Bookings",
  "customer.notes_title": "Internal notes",
  "customer.notes_empty": "No notes yet. Add one any time.",

  // Integrations
  "integrations.title": "Integrations",
  "integrations.subtitle": "{name} reads and writes to these tools · all on your accounts",
  "integrations.read": "Read",
  "integrations.write": "Write",
  "integrations.status_ok": "Connected",
  "integrations.status_idle": "Idle",
  "integrations.status_error": "Needs attention",
  "integrations.owned": "Owned by {client}",
  "integrations.empty_title": "No integrations configured yet",
  "integrations.empty_desc": "Tools connected to your agent will appear here with read/write scopes, status, and the recent activity per integration.",

  // Analytics
  "analytics.title": "Analytics",
  "analytics.desc": "Patterns across the past 30 days.",
  "analytics.hourly_title": "When customers reach out",
  "analytics.hourly_desc": "Hour-by-hour conversation volume.",
  "analytics.funnel_title": "Conversion funnel",
  "analytics.topics_title": "What they ask about",
  "analytics.topics_desc": "Auto-bucketed from the first message.",
  "analytics.empty": "Not enough data yet for this chart. Check back after a week of activity.",

  // Settings
  "settings.title": "Settings",
  "settings.desc": "Account, plan, and system history.",
  "settings.tab_billing": "Plan & billing",
  "settings.tab_activity": "System history",
  "settings.tab_language": "Language & preferences",
  "settings.plan_title": "Your Loucels plan",
  "settings.plan_eyebrow": "Monthly summary",
  "settings.plan_monthly": "Monthly cost",
  "settings.plan_monthly_sub": "Flat fee. Includes infra, maintenance, and support.",
  "settings.plan_agents": "Agents included",
  "settings.plan_client_since": "Customer since",
  "settings.plan_portal_activated": "Portal activated {date}",
  "settings.includes_title": "What's included",
  "settings.includes_eyebrow": "Operationals with Steven",
  "settings.account_title": "Account details",
  "settings.account_eyebrow": "Contact info",
  "settings.account_legal": "Legal name",
  "settings.account_vertical": "Vertical",
  "settings.account_language": "Language",
  "settings.account_email": "Billing email",
  "settings.account_update": "Update info",
  "settings.billing_help": "Question about your invoice? Email billing@loucels.com or Steven directly. Invoices land on the first of the month via Stripe.",
  "settings.lang_title": "Display language",
  "settings.lang_desc": "Affects every page in this portal. We'll remember your choice.",
  "settings.lang_en": "English",
  "settings.lang_es": "Spanish",
  "settings.lang_save": "Save preference",
  "settings.lang_saved": "Saved",

  // Common
  "btn.back": "Back",
  "btn.cancel": "Cancel",
  "btn.save": "Save",
  "common.relative_now": "now",
  "common.confirmation_pending": "Confirmation in 1 business hour",
};

const ES: Dict = {
  "nav.activity": "Actividad",
  "nav.resumen": "Resumen",
  "nav.bandeja": "Bandeja",
  "nav.requires_action": "Requiere acción",
  "nav.your_agents": "Tus agentes",
  "nav.insights": "Análisis",
  "nav.customers": "Clientes",
  "nav.integrations": "Integraciones",
  "nav.analytics": "Analytics",
  "nav.account": "Cuenta",
  "nav.settings": "Configuración",
  "nav.support": "Soporte",
  "session.7day": "Sesión de 7 días",

  "resumen.eyebrow": "Últimos 7 días · en vivo",
  "resumen.greeting": "Hola, {name}",
  "resumen.desc": "Esto es lo que tu agente hizo por {client} esta semana. Si algo necesita tu cerebro, lo verás abajo en grande.",
  "resumen.recap_title": "Resumen Loucels",
  "resumen.cta_pending": "{n} aprobación{plural} pendiente{plural}",
  "resumen.cta_view_inbox": "Ver bandeja",

  "metric.leads": "Leads procesados",
  "metric.leads_sub": "Conversaciones · últimos {n} días",
  "metric.bookings": "Citas confirmadas",
  "metric.bookings_sub": "En tu calendario",
  "metric.hours": "Horas recuperadas",
  "metric.hours_sub": "Estimado · {n} min por conversación",

  "money.clear_eyebrow": "Todo bajo control",
  "money.clear_title": "Tu agente trabajó solo esta semana.",
  "money.clear_desc": "No hay nada esperando tu aprobación. El agente actuó dentro de las reglas que definimos juntos.",
  "money.alert_eyebrow": "Acción requerida",
  "money.alert_title": "{n} aprobación{plural} esperándote",
  "money.alert_desc": "Tu agente preparó {n} acción{plural} pero quiere tu visto bueno antes de enviar.",
  "money.high_risk": "Hay al menos una de riesgo alto.",
  "money.review_now": "Revisar ahora",
  "money.more": "+{n} más",

  "today.title": "Hoy en el calendario",
  "today.empty": "Nada agendado para hoy aún.",
  "today.more": "+{n} más más tarde",

  "live.title": "Actividad en vivo",
  "live.empty": "Cuando tu agente esté ocupado, verás las acciones aquí.",
  "live.refresh": "actualiza solo",

  "inbox.title": "Bandeja",
  "inbox.desc": "Cada conversación entre tus clientes y el agente, en limpio.",
  "inbox.count": "{n} conversación{plural} en los últimos 30 días.",
  "inbox.search_soon": "Buscar (próximamente)",
  "inbox.visitor": "Visitante {short}",
  "inbox.empty_title": "Sin conversaciones todavía",
  "inbox.empty_desc": "Cuando alguien hable con tu agente, la charla aparecerá aquí en lenguaje natural.",
  "inbox.select_one": "Elige una conversación a la izquierda.",
  "inbox.tag_apply": "Etiquetar",
  "inbox.tag_filter": "Filtrar por etiqueta",
  "inbox.take_over": "Tomar control",
  "inbox.take_over_active": "Estás llevando esta conversación",
  "inbox.take_over_release": "Devolver al agente",
  "inbox.send_as_owner": "Enviar como tú",
  "inbox.send": "Enviar",
  "inbox.composer_placeholder": "Escribe tu mensaje…",
  "inbox.agent_paused": "Agente en pausa. Estás manejando esta conversación a mano.",

  "tag.complaint": "Queja",
  "tag.booking": "Cita",
  "tag.info_request": "Información",
  "tag.follow_up": "Seguimiento",
  "tag.spam": "Spam",
  "tag.vip": "VIP",
  "tag.urgent": "Urgente",
  "tag.sale_lost": "Venta perdida",
  "tag.sale_won": "Venta ganada",

  "ra.title": "Requiere acción",
  "ra.subtitle_pending": "{n} acción{plural} esperando tu visto bueno.",
  "ra.subtitle_empty": "Tu agente está despachando solo. Nada que decidir.",
  "ra.subtitle_no_agent": "Espacio reservado para futuras aprobaciones.",
  "ra.history_title": "Historial de decisiones",
  "ra.history_eyebrow": "Últimas 20",
  "ra.clear_title": "Todo bajo control",
  "ra.clear_desc": "Tu agente actuó dentro de las reglas. Nada esperando tu aprobación.",
  "ra.action.send_message": "Enviar mensaje",
  "ra.action.send_quote": "Enviar cotización",
  "ra.action.send_refund": "Procesar reembolso",
  "ra.action.reply_review": "Responder reseña",
  "ra.high_risk": "Riesgo alto",
  "ra.medium_risk": "Riesgo medio",
  "ra.proposed_label": "El agente quiere enviar:",
  "ra.edit_label": "Edita el mensaje",
  "ra.reject_label": "¿Por qué? (opcional)",
  "ra.reject_placeholder": "Lo escribiré yo / información incorrecta / no estoy listo todavía",
  "ra.btn_approve": "Aprobar y enviar",
  "ra.btn_modify": "Modificar",
  "ra.btn_reject": "Rechazar",
  "ra.btn_approve_edited": "Aprobar versión editada",
  "ra.btn_confirm_reject": "Confirmar rechazo",
  "ra.btn_cancel": "Cancelar",
  "ra.btn_back": "Atrás",
  "ra.realtime_hint": "Se envía al instante por email",
  "ra.stub_hint": "Confirmación en 1 hora hábil",
  "ra.approved_realtime": "Enviado",
  "ra.approved_stub": "Aprobado",
  "ra.approved_realtime_desc": "El mensaje salió al instante.",
  "ra.approved_stub_desc": "Loucels lo está ejecutando — confirmación en 1 hora hábil.",
  "ra.rejected": "Rechazado",
  "ra.rejected_desc": "El agente no enviará esta acción.",
  "ra.error": "No pudimos procesar la acción ({reason}). Inténtalo de nuevo o escribe a steven@loucels.com.",
  "ra.recipient": "Destinatario",

  "customers.title": "Clientes",
  "customers.desc": "Todos los que han hablado con tu agente — sesiones, citas, historial.",
  "customers.empty_title": "Sin clientes todavía",
  "customers.empty_desc": "Cuando los visitantes comiencen a chatear, aparecerán aquí como perfiles que puedes explorar.",
  "customers.count": "{n} personas únicas",
  "customers.col_name": "Nombre",
  "customers.col_sessions": "Sesiones",
  "customers.col_bookings": "Citas",
  "customers.col_first": "Primera",
  "customers.col_last": "Última",

  "customer.back": "Todos los clientes",
  "customer.history_title": "Historial de conversaciones",
  "customer.bookings_title": "Citas",
  "customer.notes_title": "Notas internas",
  "customer.notes_empty": "Sin notas todavía. Puedes agregar una cuando quieras.",

  "integrations.title": "Integraciones",
  "integrations.subtitle": "{name} lee y escribe en estas herramientas · todo en tus cuentas",
  "integrations.read": "Lectura",
  "integrations.write": "Escritura",
  "integrations.status_ok": "Conectado",
  "integrations.status_idle": "En reposo",
  "integrations.status_error": "Requiere atención",
  "integrations.owned": "Propiedad de {client}",
  "integrations.empty_title": "Sin integraciones configuradas todavía",
  "integrations.empty_desc": "Las herramientas conectadas a tu agente aparecerán aquí con sus permisos, estado y actividad reciente.",

  "analytics.title": "Analytics",
  "analytics.desc": "Patrones de los últimos 30 días.",
  "analytics.hourly_title": "Cuándo te contactan",
  "analytics.hourly_desc": "Volumen de conversaciones hora por hora.",
  "analytics.funnel_title": "Embudo de conversión",
  "analytics.topics_title": "Sobre qué preguntan",
  "analytics.topics_desc": "Agrupado automáticamente desde el primer mensaje.",
  "analytics.empty": "Sin datos suficientes para este gráfico. Vuelve después de una semana de actividad.",

  "settings.title": "Configuración",
  "settings.desc": "Cuenta, plan, e historial del sistema.",
  "settings.tab_billing": "Plan y facturación",
  "settings.tab_activity": "Historial del sistema",
  "settings.tab_language": "Idioma y preferencias",
  "settings.plan_title": "Tu plan con Loucels",
  "settings.plan_eyebrow": "Resumen mensual",
  "settings.plan_monthly": "Costo mensual",
  "settings.plan_monthly_sub": "Tarifa fija. Incluye infraestructura, mantenimiento y soporte.",
  "settings.plan_agents": "Agentes incluidos",
  "settings.plan_client_since": "Cliente desde",
  "settings.plan_portal_activated": "Portal activado {date}",
  "settings.includes_title": "Qué incluye",
  "settings.includes_eyebrow": "Operativos con Steven",
  "settings.account_title": "Datos de tu cuenta",
  "settings.account_eyebrow": "Información de contacto",
  "settings.account_legal": "Razón social",
  "settings.account_vertical": "Vertical",
  "settings.account_language": "Idioma",
  "settings.account_email": "Correo de facturación",
  "settings.account_update": "Actualizar datos",
  "settings.billing_help": "¿Pregunta sobre tu factura? Escribe a billing@loucels.com o directamente a Steven. Las facturas llegan el primer día del mes vía Stripe.",
  "settings.lang_title": "Idioma del portal",
  "settings.lang_desc": "Afecta cada página del portal. Recordamos tu elección.",
  "settings.lang_en": "Inglés",
  "settings.lang_es": "Español",
  "settings.lang_save": "Guardar preferencia",
  "settings.lang_saved": "Guardado",

  "btn.back": "Atrás",
  "btn.cancel": "Cancelar",
  "btn.save": "Guardar",
  "common.relative_now": "ahora",
  "common.confirmation_pending": "Confirmación en 1 hora hábil",
};

const DICTS: Record<PortalLang, Dict> = { en: EN, es: ES };

export function t(lang: PortalLang, key: string, params?: Record<string, string | number>): string {
  const raw = DICTS[lang]?.[key] ?? DICTS.en[key] ?? key;
  if (!params) return raw;
  return raw.replace(/\{(\w+)\}/g, (_m, k: string) => {
    const v = params[k];
    return v === undefined ? `{${k}}` : String(v);
  });
}

/** Convenience: pluralize helper. Returns "s" for non-1, "" otherwise. */
export function pl(n: number, en: string = "s", es: string = "es", lang: PortalLang = "en"): string {
  return n === 1 ? "" : lang === "es" ? es : en;
}
